baseurl: /dslectures/
collections:
  tooltips:
    output: false
company_name: fast.ai
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: Writing a library entirely in notebooks
exclude:
- vendor
google_analytics: null
google_search: 000837339549978028235:vh0pq0omtgr
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  math_engine: katex
  syntax_highlighter: rouge
markdown: kramdown
output: web
permalink: pretty
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: fastai/nbdev
sidebars:
- home_sidebar
site_title: dslectures
topnav_title: dslectures
twitter_username: fastdotai
use_math: true
